### ISSUE TITLE
Question: Did you manage to get the console to trigger the email handler on the worker?

### ISSUE THREAD

**Issue by bn-l** [webbertakken/email-worker#40]
I saw your question [here](https://www.answeroverflow.com/m/1079085311465902160) on a stackoverflow scraper (SO doesn't rank at all on google for the error message: "Email Trigger not available to this workers").

Did you manage to get the console next to the code editor working?

**Comment by webbertakken** [comment]
I'm not really in context of that anymore, but I just checked. Here's what I can say:

- The repo is still a good working example
- I can open the "Edit code" view
- It shows a different error instead of malfunctioning altogether

> .internal-f0f1e173-d2b2-4572-b0f4-76f5471a5a8a-facade-1.js:14 **Error: No fetch handler!**
    at __facade_modules_fetch__ (.internal-f0f1e173-d2b2-4572-b0f4-76f5471a5a8a-loader.js:23:38)
    at __facade_invokeChain__ (.internal-f0f1e173-d2b2-4572-b0f4-76f5471a5a8a-common.js:16:10)
    at Object.next (.internal-f0f1e173-d2b2-4572-b0f4-76f5471a5a8a-common.js:13:14)
    at jsonError (.internal-f0f1e173-d2b2-4572-b0f4-76f5471a5a8a-facade-1.js:12:32)
    at __facade_invokeChain__ (.internal-f0f1e173-d2b2-4572-b0f4-76f5471a5a8a-common.js:16:10)
    at Object.next (.internal-f0f1e173-d2b2-4572-b0f4-76f5471a5a8a-common.js:13:14)
    at scheduled (.internal-f0f1e173-d2b2-4572-b0f4-76f5471a5a8a-facade-0.js:9:24)
    at __facade_invokeChain__ (.internal-f0f1e173-d2b2-4572-b0f4-76f5471a5a8a-common.js:16:10)
    at __facade_invoke__ (.internal-f0f1e173-d2b2-4572-b0f4-76f5471a5a8a-common.js:19:10)

- The interface for sending a test email seems to be gone entirely

i.e. instead of this:

![image](https://github.com/webbertakken/email-worker/assets/20756439/c77e5b69-71cf-4e75-a964-9a42573b7424)

There's now this:

![image](https://github.com/webbertakken/email-worker/assets/20756439/5271d83d-4246-4a90-aa80-dabf30bbc797)

Looks like they've moved from their proprietary editor to a webbased implementation of VS Code, which no longer has any notion of emails.

Recommend using the official docs @ https://developers.cloudflare.com/email-routing/email-workers/

**Comment by webbertakken** [comment]
Reading in [the docs](https://developers.cloudflare.com/email-routing/email-workers/edit-email-workers/), I now remember that you have to access email workers through `Email > Email Routing > Email Workers` to access it through the email specific editor, which seems to still be the old editor.

I see that the email trigger is not available still. However that might be because I haven't updated my wrangler config for a while.

![image](https://github.com/webbertakken/email-worker/assets/20756439/81709c44-c038-4e88-b280-09880dc9e029)

**Comment by webbertakken** [comment]
Just updated all deps #41 and wrangler and wrangler config #42. 

The result is the same in the console: `Email Trigger not available to this workers`

**Comment by bn-l** [comment]
Wow huge thanks for A: getting back to me and B: such a thorough response. Very appreciative. 

So as it stands now the console is definitely bugged but emails _are_ triggering the "email" handler (this is from my own testing also).

I hope someone googling that error finds this thread.

**Comment by badilaa-ppb** [comment]
Hi all,

I have the same error how did you managed to test it?

**Comment by webbertakken** [comment]
For unit / integration testing, there's the automated tests that you can find in the repo.

For the end-to-end test I just sent an email myself and verified that it sent the message to the discord channel (see screenshot above).

**Comment by badilaa-ppb** [comment]
Thank you, how did you log the message?
